GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "dave",
  "email": "dave@example.com",
  "password": "password"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "dave",
  "password": "password"
}